schema_version = 1
name = "nvim"
description = "Neovim configuration"
supported_os = ["linux", "darwin"]

[profiles.common]
sources = [{path = ".config/nvim", mode = "folder", target = "$HOME/.config/nvim"}]
